# Generated by Django 5.0.9 on 2026-09-01 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyManagmentCompanyRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'property_propertymanagmentcompany',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinancePMCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmc_id', models.BigIntegerField(help_text='units-backend PropertyManagmentCompany.id — not a cross-DB FK (AD-19).')),
                ('base_currency', models.CharField(default='AED', max_length=3)),
                ('country', models.CharField(max_length=100)),
                ('fiscal_year_start_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
