# Generated by Django 5.0.9 on 2026-09-01 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Income', 'Income'), ('Expense', 'Expense'), ('Equity', 'Equity')], max_length=20)),
                ('finance_pmc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='ledger.financepmcprofile')),
            ],
        ),
    ]
