# Generated by Django 5.0.9 on 2026-09-01 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.BigIntegerField(help_text='units-backend Unit.id — not a cross-DB FK (next hop toward the PMC).')),
            ],
            options={
                'db_table': 'lease_lease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeaseTransactionRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_id', models.BigIntegerField(help_text='units-backend Lease.id — not a cross-DB FK (next hop toward the PMC).')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('cheque_type', models.CharField(max_length=20)),
                ('payment_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'lease_leasetransaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmc_id', models.BigIntegerField(blank=True, help_text='units-backend PropertyManagmentCompany.id — matches FinancePMCProfile.pmc_id (AD-19).', null=True)),
            ],
            options={
                'db_table': 'property_property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_property_id', models.BigIntegerField(blank=True, help_text='units-backend Property.id — not a cross-DB FK (next hop toward the PMC).', null=True)),
            ],
            options={
                'db_table': 'property_unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lease_transaction_id', models.BigIntegerField(help_text='units-backend LeaseTransaction.id — not a cross-DB FK (AD-19 precedent).')),
                ('source_status_transition', models.CharField(help_text='Exact FROM_STATUS->TO_STATUS pair; idempotency key with source_lease_transaction_id (AD-14).', max_length=100)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('finance_pmc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='ledger.financepmcprofile')),
                ('reversed_journal_entry', models.ForeignKey(blank=True, help_text="FK to the original entry if this is a reversal; additive-only reversals, unused until Story 2.6 (AD-16). Django auto-derives the 'reversed_journal_entry_id' db column from this field name, matching the ARCHITECTURE-SPINE ER diagram's column name exactly.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversing_entries', to='ledger.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_lines', to='ledger.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry')),
            ],
        ),
    ]
