# Generated by Django 5.0.9 on 2026-09-02 08:23
#
# Story 4.1: new Finance-owned BankStatementLine table (spec Code Map --
# "new real (not no-op) migration"). Django's makemigrations also proposed an
# AlterField on JournalEntry.reversed_journal_entry (a help_text-only diff
# left over from a prior story's docstring edit, out of scope here) --
# deliberately dropped from this migration so it stays scoped to this story's
# actual model change.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_lease_transaction_cheque_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(max_length=255)),
                ('reconciled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('finance_pmc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_lines', to='ledger.financepmcprofile')),
            ],
        ),
    ]
